"""Typed boundaries for the untyped Arrow runtime used by native source transport."""

from collections.abc import Mapping
from contextlib import AbstractContextManager
from io import BytesIO
from typing import Protocol


class ArrowTable(Protocol):
    num_rows: int
    schema: object

    def __getitem__(self, key: str | int) -> object: ...
    def combine_chunks(self) -> 'ArrowTable': ...
    def slice(self, offset: int, length: int) -> 'ArrowTable': ...
    def set_column(self, index: int, name: str, data: object) -> 'ArrowTable': ...
    def append_column(self, name: str, data: object) -> 'ArrowTable': ...


class ArrowBuffer(Protocol):
    def to_pybytes(self) -> bytes: ...


class ArrowSink(Protocol):
    def getvalue(self) -> ArrowBuffer: ...


class ArrowWriter(Protocol):
    def write_table(self, table: ArrowTable, *, max_chunksize: int) -> None: ...


class ArrowModule(Protocol):
    def uint64(self) -> object: ...
    def uint8(self) -> object: ...
    def int64(self) -> object: ...
    def float64(self) -> object: ...
    def bool_(self) -> object: ...
    def timestamp(self, unit: str, *, tz: str) -> object: ...
    def BufferOutputStream(self) -> ArrowSink: ...


class ArrowIPC(Protocol):
    def new_stream(
        self, sink: ArrowSink, schema: object
    ) -> AbstractContextManager[ArrowWriter]: ...


class ArrowCSV(Protocol):
    def read_csv(
        self, body: BytesIO, *, read_options: object, convert_options: object
    ) -> ArrowTable: ...
    def ReadOptions(self, *, column_names: list[str]) -> object: ...
    def ConvertOptions(
        self, *, column_types: Mapping[str, object], true_values: list[str], false_values: list[str]
    ) -> object: ...


class ArrowCompute(Protocol):
    def if_else(self, cond: object, left: object, right: object) -> object: ...
    def less(self, left: object, right: object) -> object: ...
    def multiply(self, left: object, right: object) -> object: ...
    def cast(self, data: object, dtype: object) -> object: ...
