from typing import Any

class Client:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def execute(self, *args: Any, **kwargs: Any) -> Any: ...
    def disconnect(self) -> None: ...
