from typing import Any

class Client:
    def query_arrow(self, *args: Any, **kwargs: Any) -> Any: ...
    def query(self, *args: Any, **kwargs: Any) -> Any: ...
    def command(self, *args: Any, **kwargs: Any) -> Any: ...
    def insert_arrow(self, *args: Any, **kwargs: Any) -> Any: ...
    def close(self) -> None: ...

def get_client(*args: Any, **kwargs: Any) -> Client: ...
